// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwwY2RkUyr1MTuXyQVaa-jE5kVGGR9EDM',
    appId: '1:791729577192:web:64d69098e12afbc7653d5d',
    messagingSenderId: '791729577192',
    projectId: 'macromate-f6c6d',
    authDomain: 'macromate-f6c6d.firebaseapp.com',
    storageBucket: 'macromate-f6c6d.firebasestorage.app',
    measurementId: 'G-2GPVRMR2Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ieVLAP6fCzmV0wCmNvtkX2Wcsp94CVM',
    appId: '1:791729577192:android:1a20d225f5697a99653d5d',
    messagingSenderId: '791729577192',
    projectId: 'macromate-f6c6d',
    storageBucket: 'macromate-f6c6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQAVe3N0cJ1_zcFlNZhywGFMf3UrGXvUk',
    appId: '1:791729577192:ios:03a201ff959958f4653d5d',
    messagingSenderId: '791729577192',
    projectId: 'macromate-f6c6d',
    storageBucket: 'macromate-f6c6d.firebasestorage.app',
    iosClientId: '791729577192-u5og3in4h8im9hac7h56hs03bp1crbjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.macroTrackerAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwwY2RkUyr1MTuXyQVaa-jE5kVGGR9EDM',
    appId: '1:791729577192:web:cc7c192dda13edd0653d5d',
    messagingSenderId: '791729577192',
    projectId: 'macromate-f6c6d',
    authDomain: 'macromate-f6c6d.firebaseapp.com',
    storageBucket: 'macromate-f6c6d.firebasestorage.app',
    measurementId: 'G-8YKXB8DR2N',
  );
}
